# ansible/site.yml（全置換）
---
- name: Configure this node via ansible-pull (Web only)
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  roles:
    - role: common
    - role: web
    - role: cloudwatch_agent
