---
- hosts: all
  gather_facts: true
  roles:
    - common

- hosts: redis
  roles:
    - redis_vm

- hosts: minio
  roles:
    - minio_vm

- hosts: web
  roles:
    - edunotes_web_vm

- hosts: monitor
  roles:
    - prometheus_vm
