- name: Fetch MinIO creds from SSM
  set_fact:
    minio_access_key: "{{ lookup('amazon.aws.aws_ssm', ssm_minio_access_key, decrypt=true, region=lookup('env','AWS_REGION')|default('ap-northeast-3', true)) }}"
    minio_secret_key: "{{ lookup('amazon.aws.aws_ssm', ssm_minio_secret_key, decrypt=true, region=lookup('env','AWS_REGION')|default('ap-northeast-3', true)) }}"

- name: Install MinIO binary
  ansible.builtin.get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin/minio
    mode: '0755'

- name: Create data dir
  ansible.builtin.file:
    path: /var/minio
    state: directory
    mode: '0755'

- name: Install mc (client)
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin/mc
    mode: '0755'

- name: Install service
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service

- name: Start MinIO
  ansible.builtin.systemd:
    name: minio
    enabled: true
    state: started

- name: Init bucket script
  ansible.builtin.template:
    src: minio-init.sh.j2
    dest: /root/minio-init.sh
    mode: '0755'

- name: Create bucket
  ansible.builtin.command: /root/minio-init.sh
  changed_when: false
