---
# 1) パッケージ
- name: Install base packages
  apt:
    name:
      - curl
      - gnupg
      - nginx
      - git
      - build-essential
    state: present
    update_cache: yes

# 2) Node.js 20 (NodeSource)
- name: Setup NodeSource repo
  shell: |
    set -e
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  args:
    executable: /bin/bash

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

# 3) アプリ用ユーザー/ディレクトリ（★ホーム作成＆/bin/bash）
- name: Ensure app group
  group:
    name: edunotes
    system: yes

- name: Ensure app user
  user:
    name: edunotes
    group: edunotes
    system: yes
    shell: /bin/bash          # ← 変更点
    create_home: yes          # ← 変更点
    home: /home/edunotes      # ← 追加（明示）

- name: Ensure HOME, npm cache, and ansible tmp
  file:
    path: "{{ item }}"
    state: directory
    owner: edunotes
    group: edunotes
    mode: "0755"
  loop:
    - /home/edunotes
    - /home/edunotes/.npm
    - /home/edunotes/.ansible/tmp

- name: Create app and etc dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: edunotes
    group: edunotes
    mode: "0755"
  loop:
    - /opt/edunotes
    - /etc/edunotes
    - /var/edunotes/uploads

# 4) アプリ取得（環境変数 APP_REPO_URL / APP_REPO_BRANCH を想定）
- name: Set default app repo vars
  set_fact:
    app_repo: "{{ lookup('env','APP_REPO_URL') | default('', true) }}"
    app_branch: "{{ lookup('env','APP_REPO_BRANCH') | default('main', true) }}"

- name: Clone app repository (optional)
  git:
    repo: "{{ app_repo }}"
    version: "{{ app_branch }}"
    dest: /opt/edunotes          # ← /opt/edunotes 直下に配置
    force: yes
  when: app_repo | length > 0
  become: true                    # ← 追加
  become_user: edunotes

- name: Install dependencies (ci if lock, else install)
  shell: |
    set -e
    cd /opt/edunotes
    if [ -f package-lock.json ]; then
      npm ci --production
    elif [ -f package.json ]; then
      npm install --production
    fi
  args:
    executable: /bin/bash
  when: app_repo | length > 0
  become: true                    # ← 追加
  become_user: edunotes
  environment:                    # ← 追加（EACCES回避）
    HOME: /home/edunotes
    npm_config_cache: /home/edunotes/.npm

# 4.5) repo 未設定でも /healthz を上げる “保険” の最小アプリ
- name: Seed minimal app when repo is not provided
  block:
    - name: Create minimal server.js
      copy:
        dest: /opt/edunotes/server.js
        owner: edunotes
        group: edunotes
        mode: "0644"
        content: |
          const express = require("express");
          const app = express();
          app.get("/", (req,res)=>res.send("ok"));
          app.get("/healthz",(req,res)=>res.send("ok"));
          app.get("/readyz",(req,res)=>res.send("ok"));
          app.get("/metrics",(req,res)=>res.type("text/plain").send("# HELP dummy 1\n# TYPE dummy counter\ndummy 1\n"));
          const port = process.env.PORT || 3000;
          app.listen(port, ()=>console.log("listen", port));

    - name: Init package.json if missing
      command: npm init -y
      args:
        chdir: /opt/edunotes
        creates: /opt/edunotes/package.json
      become: true
      become_user: edunotes
      environment:
        HOME: /home/edunotes
        npm_config_cache: /home/edunotes/.npm

    - name: Install express for minimal app
      command: npm install express --production
      args:
        chdir: /opt/edunotes
      become: true
      become_user: edunotes
      environment:
        HOME: /home/edunotes
        npm_config_cache: /home/edunotes/.npm
  when: app_repo | length == 0

# 5) .env（フェーズ1：ローカル添付・非Redis）
- name: Render env file
  template:
    src: envfile.j2
    dest: /etc/edunotes/env
    owner: edunotes
    group: edunotes
    mode: "0640"

# 6) Nginx vhost（Ubuntu流儀）
- name: Render nginx vhost
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/edunotes.conf
    mode: "0644"

- name: Enable nginx vhost
  file:
    src: /etc/nginx/sites-available/edunotes.conf
    dest: /etc/nginx/sites-enabled/edunotes.conf
    state: link
    force: yes

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test nginx config
  command: nginx -t
  register: nginx_test
  changed_when: false
  notify: Restart nginx

# 7) systemd unit（非root）
- name: Render systemd service
  template:
    src: edunotes.service.j2
    dest: /etc/systemd/system/edunotes.service
    mode: "0644"

- name: daemon-reload
  systemd:
    daemon_reload: true

- name: Start & enable app
  systemd:
    name: edunotes
    enabled: true
    state: started

# 8) ヘルスチェック (/healthz が 200 を返すこと)
- name: Wait for healthz
  uri:
    url: http://127.0.0.1:3000/healthz
    status_code: 200
  register: health
  retries: 30
  delay: 3
  until: health.status == 200
