# ansible/roles/web/tasks/main.yml（全置換）
---
# 1) パッケージ
- name: Install base packages
  apt:
    name:
      - curl
      - gnupg
      - nginx
      - git
      - build-essential
    state: present
    update_cache: yes

# 2) Node.js 20 (NodeSource)
- name: Setup NodeSource repo
  shell: |
    set -e
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  args:
    executable: /bin/bash

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

# 3) アプリ用ユーザー/ディレクトリ
- name: Ensure app group
  group:
    name: edunotes
    system: yes

- name: Ensure app user
  user:
    name: edunotes
    group: edunotes
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: edunotes
    group: edunotes
    mode: "0755"
  loop:
    - /opt/edunotes
    - /etc/edunotes
    - /var/edunotes/uploads

# 4) アプリ取得（環境変数 APP_REPO_URL / APP_REPO_BRANCH を想定）
- name: Set default app repo vars
  set_fact:
    app_repo: "{{ lookup('env','APP_REPO_URL') | default('', true) }}"
    app_branch: "{{ lookup('env','APP_REPO_BRANCH') | default('main', true) }}"

- name: Clone app repository (optional)
  git:
    repo: "{{ app_repo }}"
    version: "{{ app_branch }}"
    dest: /opt/edunotes
    force: yes
  when: app_repo | length > 0
  become_user: edunotes

- name: Install dependencies (npm ci)
  community.general.npm:
    path: /opt/edunotes
    production: true
    ci: true
  when: app_repo | length > 0
  become_user: edunotes

# 5) .env（フェーズ1：ローカル添付・非Redis）
- name: Render env file
  template:
    src: envfile.j2
    dest: /etc/edunotes/env
    owner: edunotes
    group: edunotes
    mode: "0640"

# 6) Nginx vhost（Ubuntu流儀）
- name: Render nginx vhost
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/edunotes.conf
    mode: "0644"

- name: Enable nginx vhost
  file:
    src: /etc/nginx/sites-available/edunotes.conf
    dest: /etc/nginx/sites-enabled/edunotes.conf
    state: link
    force: yes

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test and restart nginx
  command: nginx -t
  register: nginx_test
  changed_when: false
  notify: Restart nginx

# 7) systemd unit（非root）
- name: Render systemd service
  template:
    src: edunotes.service.j2
    dest: /etc/systemd/system/edunotes.service
    mode: "0644"

- name: daemon-reload
  systemd:
    daemon_reload: true

- name: Start & enable app
  systemd:
    name: edunotes
    enabled: true
    state: started

# 8) ヘルスチェック (/healthz が 200 を返すこと)
- name: Wait for healthz
  uri:
    url: http://127.0.0.1:3000/healthz
    status_code: 200
  register: health
  retries: 30
  delay: 3
  until: health.status == 200

# Handlers
- name: Restart nginx
  listen: Restart nginx
  service:
    name: nginx
    state: restarted
