- name: Install CloudWatch Agent
  become: true
  apt:
    name: amazon-cloudwatch-agent
    state: present
    update_cache: yes

- name: Ensure app log dir exists
  become: true
  file:
    path: /var/log/edunotes
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Put cwagent config
  become: true
  copy:
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    content: |
      {
        "metrics": {
          "append_dimensions": { "AutoScalingGroupName": "${aws:AutoScalingGroupName}" },
          "metrics_collected": {
            "mem":  { "measurement": ["mem_used_percent"], "metrics_collection_interval": 60 },
            "disk": { "resources": ["*"], "measurement": ["used_percent"], "metrics_collection_interval": 60 },
            "swap": { "measurement": ["swap_used_percent"], "metrics_collection_interval": 60 },
            "netstat": { "measurement": ["tcp_established","tcp_time_wait"], "metrics_collection_interval": 60 }
          }
        },
        "logs": {
          "logs_collected": {
            "files": {
              "collect_list": [
                { "file_path": "/var/log/nginx/access.log", "log_group_name": "/edunotes/nginx/access", "log_stream_name": "{instance_id}" },
                { "file_path": "/var/log/nginx/error.log",  "log_group_name": "/edunotes/nginx/error",  "log_stream_name": "{instance_id}" },
                { "file_path": "/var/log/edunotes/app.log", "log_group_name": "/edunotes/app",         "log_stream_name": "{instance_id}" }
              ]
            }
          }
        }
      }
  notify: Restart cwagent

- name: Enable & start cwagent
  become: true
  systemd:
    name: amazon-cloudwatch-agent
    enabled: true
    state: started
